export const GET_DECK_LIST_LOADING = "GET_DECK_LIST_LOADING";
export const GET_DECK_LIST_SUCCESS = "GET_DECK_LIST_SUCCESS";
export const GET_DECK_LIST_FAIL = "GET_DECK_LIST_FAIL";

export const GET_TYPE_LIST_LOADING = "GET_TYPE_LIST_LOADING";
export const GET_TYPE_LIST_SUCCESS = "GET_TYPE_LIST_SUCCESS";
export const GET_TYPE_LIST_FAIL = "GET_TYPE_LIST_FAIL";
